CREATE TABLE photos(
   id INT AUTO_INCREMENT PRIMARY KEY,
   title VARCHAR(255) NOT NUll,
   image_path VARCHAR(255) NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON update CURRENT_TIMESTAMP
)
